In [51]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [52]:
df = pd.read_csv("C:/Users/Likhi/OneDrive/Documents/MachineLearning/homeprices(2).csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [53]:
import math
median_bedroom = math.floor(df.bedrooms.median())
median_bedroom

4

In [54]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [55]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [56]:
#price  = m1 * area + m2 * bedrooms + m3 * age + intercept
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [57]:
reg.intercept_

221323.00186540408

In [58]:
reg.predict([[3000,3,40]])

C:\Users\Likhi\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [59]:
reg.predict([[2500,4,5]])

C:\Users\Likhi\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [60]:
#Assignment 
df2 = pd.read_csv("C:/Users/Likhi/OneDrive/Documents/MachineLearning/hiring.csv")
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [61]:
from word2number import w2n

In [62]:
# Function to convert words to numbers using word2number
def convert_experience_to_number(exp):
    try:
        return w2n.word_to_num(exp)
    except:
        return np.nan

# Apply the function to the 'experience' column
df2['experience'] = df2['experience'].apply(lambda x: convert_experience_to_number(x) if isinstance(x, str) else x)

# Use pd.to_numeric to ensure the column is numeric and handle NaN values
df2['experience'] = pd.to_numeric(df2['experience'], errors='coerce')

print(df2)

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000


In [64]:
df2['experience']=df2.experience.fillna(0)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [78]:
df2.rename(columns={'test_score(out of 10)': 'test_score','interview_score(out of 10)' : 'interview_score', 'salary($)':'salary' }, inplace=True)
df2

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [79]:
import math
df2['test_score'] = df2.test_score.fillna(df2.test_score.median())
df2

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [82]:
reg2 = linear_model.LinearRegression()
reg2.fit(df2[['experience','test_score','interview_score']],df2.salary)

LinearRegression()

In [85]:
reg2.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [86]:
reg2.intercept_

17737.26346433771

In [87]:
reg2.predict([[2,9,6]])

C:\Users\Likhi\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [88]:
2812.95487627*2 + 1845.70596798*9 + 2205.24017467*6 + 17737.26346433771

53205.967976717715

In [89]:
reg2.predict([[12,10,10]])

C:\Users\Likhi\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])